FROM envoyproxy/envoy:v1.26.0
ADD envoy.yaml /etc/envoy.yaml
CMD envoy \
    -c ${ENVOY_CONFIG} \
    --service-zone ${ENVOY_ZONE} \
    --log-level ${ENVOY_LOGLEVEL} \
    --log-path /dev/stdout \
    --log-format '{"time": "%Y-%m-%d %T.%e", "level": "%l", "type": "%n", "message": "%v"}'
